spring.application.name=categorypostgresh
server.port=9091
server.address=0.0.0.0

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=LNV126-PC.mshome.net

spring.datasource.url=jdbc:postgresql://localhost:5432/categorypostgresdb
spring.datasource.username=user
spring.datasource.password=user123

#spring.profiles.active=dev

#eureka.instance.hostname=${HOSTNAME}
#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=192.168.1.220

spring.config.import=configserver:http://localhost:9094
#spring.cloud.config.profile=default
#spring.cloud.config.profile=dev
#spring.cloud.config.profile=qa
spring.cloud.config.profile=prod

#actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=READ_ONLY
management.endpoint.refresh.enabled=true
eureka.client.refresh.enable=false

# for spring cloud bus
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
