spring:
  application:
    name: quizmongoservice

  config:
    import: "configserver:http://localhost:9094"

  profiles:
    active: prod

  data:
    mongodb:
      uri: mongodb://localhost:27017/quizdb

  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9092
  address: 192.168.1.220

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.220:8761/eureka/
    refresh:
      enable: false

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    refresh:
      enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 1

