$kind: http-request
url: http://192.168.1.128:8080/api/v2/productsubcategory/page?pageNumber=0&pageSize=10&field=id&direction=asc&search=
method: GET
queryParams:
  - key: pageNumber
    value: "0"
  - key: pageSize
    value: "10"
  - key: field
    value: id
  - key: direction
    value: asc
  - key: search
    value: ""
  - key: categoryId
    value: "1"
    disabled: true
auth:
  type: bearer
  credentials:
    token: ""
settings: {}
order: 1000
