spring.application.name=apigateway
server.port=9093
spring.output.ansi.enabled=ALWAYS



#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#spring.cloud.gateway.routes[0].id=quiz-test
#spring.cloud.gateway.routes[0].uri=http://192.168.1.220:9092
#spring.cloud.gateway.routes[0].predicates[0]=Path=/QUIZMONGOSERVICE/**

eureka.client.service-url.defaultZone=http://192.168.1.220:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


#actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=READ_ONLY

#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=192.168.1.220

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:9096/realms/sahilSeptember/protocol/openid-connect/certs