spring.application.name=springconfiguration
server.port=9094


spring.output.ansi.enabled=ALWAYS

eureka.client.service-url.defaultZone=http://192.168.1.220:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.config.server.native.search-locations=classpath:/config
spring.profiles.active=native