spring.application.name=springconfigurationfiles
server.port=9094
spring.output.ansi.enabled=ALWAYS

#to register with eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# 1 -> configure my config to take properties files from classpath (config) files
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/config

# 2 -> GITHUB configuration to take properties files from GITHUB
spring.cloud.config.server.git.uri=https://github.com/sahilvishwakarma79222/config.git

#for actuator
management.endpoints.web.exposure.include=*



